### ISSUE TITLE
TBB build fails: `error: 'source_node' in namespace 'tbb::flow' does not name a template type`

### ISSUE THREAD

**Issue by barracuda156** [traversc/qs2#2]
@traversc Could you say which TBB the source assumes? Does not work with oneTBB, it seems:

```
using C++ compiler: ‘g++-mp-13 (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0’
Warning in system2("xcrun", "--show-sdk-path", TRUE, TRUE) :
  running command ''xcrun' --show-sdk-path 2>&1' had status 64
using SDK: ‘NA’‘NA’‘NA’‘NA’‘NA’‘NA’
/opt/local/bin/g++-mp-13 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DRCPP_NO_SUGAR -I../inst/include -I.    -DIS_UTF8_LOCALE=1 -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/Rcpp/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/stringfish/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppParallel/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include   -I/opt/local/libexec/onetbb/include -DTBB_INTERFACE_NEW -fPIC  -pipe -Os -arch ppc   -c RcppExports.cpp -o RcppExports.o
/opt/local/bin/g++-mp-13 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DRCPP_NO_SUGAR -I../inst/include -I.    -DIS_UTF8_LOCALE=1 -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/Rcpp/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/stringfish/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppParallel/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include   -I/opt/local/libexec/onetbb/include -DTBB_INTERFACE_NEW -fPIC  -pipe -Os -arch ppc   -c qx_functions.cpp -o qx_functions.o
In file included from qx_functions.cpp:11:
io/multithreaded_block_module.h:280:16: error: 'source_node' in namespace 'tbb::flow' does not name a template type
  280 |     tbb::flow::source_node<OrderedBlock> reader_node;
      |                ^~~~~~~~~~~
io/multithreaded_block_module.h: In constructor 'BlockCompressReaderMT<stream_reader, decompressor, E>::BlockCompressReaderMT(stream_reader&)':
io/multithreaded_block_module.h:306:5: error: class 'BlockCompressReaderMT<stream_reader, decompressor, E>' does not have any field named 'reader_node'
  306 |     reader_node(this->myGraph,
      |     ^~~~~~~~~~~
io/multithreaded_block_module.h:363:30: error: 'reader_node' was not declared in this scope
  363 |         tbb::flow::make_edge(reader_node, decompressor_node);
      |                              ^~~~~~~~~~~
make: *** [qx_functions.o] Error 1
ERROR: compilation failed for package ‘qs2’
```

**Comment by traversc** [comment]
It assumes the version built into RcppParallel (2019 Update 8). Newer versions of TBB use `input_node` instead of `source_node` so I'll have to use some macros to switch depending on TBB version. Any pointers are appreciated.

**Comment by barracuda156** [comment]
> It assumes the version built into RcppParallel (2019 Update 8). Newer versions of TBB use `input_node` instead of `source_node` so I'll have to use some macros to switch depending on TBB version. Any pointers are appreciated.

RcppParallel allows to use external oneTBB, and that is what MacPorts uses. (I cannot switch them back to old TBB for one port, that gonna break everything else.)
So presumably there should be two codepaths, since a priori there is no way to know which TBB happens to be used on a given system.

**Comment by barracuda156** [comment]
As an example, this is what gets passed with a package that uses `rstan` (which uses `RcppParallel`):
```
/opt/local/bin/g++-mp-13 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I"../inst/include" -I"/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/StanHeaders/include/src" -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -DBOOST_MATH_OVERFLOW_ERROR_POLICY=errno_on_error -DUSE_STANC3 -D_HAS_AUTO_PTR_ETC=0 -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/BH/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/Rcpp/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppEigen/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppParallel/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/rstan/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/StanHeaders/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include   -I/opt/local/libexec/onetbb/include -DTBB_INTERFACE_NEW -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppParallel/include' -D_REENTRANT -DSTAN_THREADS -DTBB_INTERFACE_NEW   -fPIC  -pipe -Os -arch ppc   -c stanExports_model8.cc -o stanExports_model8.o
. . .
/opt/local/bin/g++-mp-13 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/local/Library/Frameworks/R.framework/Resources/lib -Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport -Wl,-rpath,/opt/local/lib/libgcc -arch ppc -o bsynth.so RcppExports.o factor_functions.o stanExports_factor_model_with_covariates.o stanExports_factor_model_without_covariates.o stanExports_model1.o stanExports_model1_gammaOmega.o stanExports_model2.o stanExports_model3.o stanExports_model4.o stanExports_model5.o stanExports_model6.o stanExports_model7.o stanExports_model8.o -L/opt/local/libexec/onetbb/lib -Wl,-rpath,/opt/local/libexec/onetbb/lib -ltbb -ltbbmalloc -L/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppParallel/lib/ -Wl,-rpath,/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppParallel/lib/ -ltbb -ltbbmalloc -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
```
So for oneTBB the flag is `-DTBB_INTERFACE_NEW`. And `RcppParallel` is supposed to know where oneTBB headers and libs are located (here no flags are passed manually to configure).

**Comment by barracuda156** [comment]
By the way, current way of handling TBB just does not work: even when it is supposedly disabled, linking to TBB is done:
```
--->  Building R-qs2
xinstall: mkdir /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-qs2/R-qs2/work/build
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-qs2/R-qs2/work/qs2" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-qs2/R-qs2/work/build --install-tests 
* installing *source* package ‘qs2’ ...
** package ‘qs2’ successfully unpacked and MD5 sums checked
** using staged installation
checking for pkg-config... /opt/local/bin/pkg-config
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether /opt/local/bin/g++-mp-13 -std=gnu++17 accepts -g... yes
C++ compiler: /opt/local/bin/g++-mp-13 -std=gnu++17
zstd 1.5.6 library detected -- skipping zstd compilation
Fixed blocksize
Not using TBB
configure: creating ./config.status
config.status: creating src/Makevars
** libs
using C++ compiler: ‘g++-mp-13 (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0’
Warning in system2("xcrun", "--show-sdk-path", TRUE, TRUE) :
  running command ''xcrun' --show-sdk-path 2>&1' had status 64
using SDK: ‘NA’‘NA’‘NA’‘NA’‘NA’‘NA’
/opt/local/bin/g++-mp-13 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DRCPP_NO_SUGAR -I../inst/include -I.    -DIS_UTF8_LOCALE=1 -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/Rcpp/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/stringfish/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppParallel/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include   -DRCPP_PARALLEL_USE_TBB=0 -I/opt/local/libexec/onetbb/include -DTBB_INTERFACE_NEW -fPIC  -pipe -Os -arch ppc   -c RcppExports.cpp -o RcppExports.o
/opt/local/bin/g++-mp-13 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DRCPP_NO_SUGAR -I../inst/include -I.    -DIS_UTF8_LOCALE=1 -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/Rcpp/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/stringfish/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppParallel/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include   -DRCPP_PARALLEL_USE_TBB=0 -I/opt/local/libexec/onetbb/include -DTBB_INTERFACE_NEW -fPIC  -pipe -Os -arch ppc   -c qx_functions.cpp -o qx_functions.o
/opt/local/bin/g++-mp-13 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/local/Library/Frameworks/R.framework/Resources/lib -Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport -Wl,-rpath,/opt/local/lib/libgcc -arch ppc -o qs2.so RcppExports.o qx_functions.o -L. -L/opt/local/lib -lzstd -L/opt/local/libexec/onetbb/lib -Wl,-rpath,/opt/local/libexec/onetbb/lib -ltbb -ltbbmalloc -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
```
(Here I do not patch anything and do not pass any configure args, letting the build do whatever it wants to.)

**Comment by traversc** [comment]
> @traversc Could you say which TBB the source assumes? Does not work with oneTBB, it seems:
> 
> ```
> using C++ compiler: ‘g++-mp-13 (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0’
> Warning in system2("xcrun", "--show-sdk-path", TRUE, TRUE) :
>   running command ''xcrun' --show-sdk-path 2>&1' had status 64
> using SDK: ‘NA’‘NA’‘NA’‘NA’‘NA’‘NA’
> /opt/local/bin/g++-mp-13 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DRCPP_NO_SUGAR -I../inst/include -I.    -DIS_UTF8_LOCALE=1 -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/Rcpp/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/stringfish/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppParallel/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include   -I/opt/local/libexec/onetbb/include -DTBB_INTERFACE_NEW -fPIC  -pipe -Os -arch ppc   -c RcppExports.cpp -o RcppExports.o
> /opt/local/bin/g++-mp-13 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DRCPP_NO_SUGAR -I../inst/include -I.    -DIS_UTF8_LOCALE=1 -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/Rcpp/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/stringfish/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppParallel/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include   -I/opt/local/libexec/onetbb/include -DTBB_INTERFACE_NEW -fPIC  -pipe -Os -arch ppc   -c qx_functions.cpp -o qx_functions.o
> In file included from qx_functions.cpp:11:
> io/multithreaded_block_module.h:280:16: error: 'source_node' in namespace 'tbb::flow' does not name a template type
>   280 |     tbb::flow::source_node<OrderedBlock> reader_node;
>       |                ^~~~~~~~~~~
> io/multithreaded_block_module.h: In constructor 'BlockCompressReaderMT<stream_reader, decompressor, E>::BlockCompressReaderMT(stream_reader&)':
> io/multithreaded_block_module.h:306:5: error: class 'BlockCompressReaderMT<stream_reader, decompressor, E>' does not have any field named 'reader_node'
>   306 |     reader_node(this->myGraph,
>       |     ^~~~~~~~~~~
> io/multithreaded_block_module.h:363:30: error: 'reader_node' was not declared in this scope
>   363 |         tbb::flow::make_edge(reader_node, decompressor_node);
>       |                              ^~~~~~~~~~~
> make: *** [qx_functions.o] Error 1
> ERROR: compilation failed for package ‘qs2’
> ```

Hopefully fixed with the latest commit. Tested on the latest version of TBB. 

`remotes::install_github("traversc/qs2", ref= "df9e1cd902a6a461bc7cc6783f716b4983e4e4fc", configure.args = " --with-TBB --with-simd=AVX2")`

**Comment by traversc** [comment]
> By the way, current way of handling TBB just does not work: even when it is supposedly disabled, linking to TBB is done:
> 
> ```
> --->  Building R-qs2
> xinstall: mkdir /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-qs2/R-qs2/work/build
> Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-qs2/R-qs2/work/qs2" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-qs2/R-qs2/work/build --install-tests 
> * installing *source* package ‘qs2’ ...
> ** package ‘qs2’ successfully unpacked and MD5 sums checked
> ** using staged installation
> checking for pkg-config... /opt/local/bin/pkg-config
> checking whether the C++ compiler works... yes
> checking for C++ compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C++ compiler... yes
> checking whether /opt/local/bin/g++-mp-13 -std=gnu++17 accepts -g... yes
> C++ compiler: /opt/local/bin/g++-mp-13 -std=gnu++17
> zstd 1.5.6 library detected -- skipping zstd compilation
> Fixed blocksize
> Not using TBB
> configure: creating ./config.status
> config.status: creating src/Makevars
> ** libs
> using C++ compiler: ‘g++-mp-13 (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0’
> Warning in system2("xcrun", "--show-sdk-path", TRUE, TRUE) :
>   running command ''xcrun' --show-sdk-path 2>&1' had status 64
> using SDK: ‘NA’‘NA’‘NA’‘NA’‘NA’‘NA’
> /opt/local/bin/g++-mp-13 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DRCPP_NO_SUGAR -I../inst/include -I.    -DIS_UTF8_LOCALE=1 -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/Rcpp/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/stringfish/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppParallel/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include   -DRCPP_PARALLEL_USE_TBB=0 -I/opt/local/libexec/onetbb/include -DTBB_INTERFACE_NEW -fPIC  -pipe -Os -arch ppc   -c RcppExports.cpp -o RcppExports.o
> /opt/local/bin/g++-mp-13 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DRCPP_NO_SUGAR -I../inst/include -I.    -DIS_UTF8_LOCALE=1 -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/Rcpp/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/stringfish/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppParallel/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include   -DRCPP_PARALLEL_USE_TBB=0 -I/opt/local/libexec/onetbb/include -DTBB_INTERFACE_NEW -fPIC  -pipe -Os -arch ppc   -c qx_functions.cpp -o qx_functions.o
> /opt/local/bin/g++-mp-13 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/local/Library/Frameworks/R.framework/Resources/lib -Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport -Wl,-rpath,/opt/local/lib/libgcc -arch ppc -o qs2.so RcppExports.o qx_functions.o -L. -L/opt/local/lib -lzstd -L/opt/local/libexec/onetbb/lib -Wl,-rpath,/opt/local/libexec/onetbb/lib -ltbb -ltbbmalloc -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
> ```
> 
> (Here I do not patch anything and do not pass any configure args, letting the build do whatever it wants to.)

I think this is fine, those flags all come from `RcppParallel`. Usage is disabled not linkage.

**Comment by barracuda156** [comment]
> > @traversc Could you say which TBB the source assumes? Does not work with oneTBB, it seems:
> 
> > 
> 
> > ```
> 
> > using C++ compiler: ‘g++-mp-13 (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0’
> 
> > Warning in system2("xcrun", "--show-sdk-path", TRUE, TRUE) :
> 
> >   running command ''xcrun' --show-sdk-path 2>&1' had status 64
> 
> > using SDK: ‘NA’‘NA’‘NA’‘NA’‘NA’‘NA’
> 
> > /opt/local/bin/g++-mp-13 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DRCPP_NO_SUGAR -I../inst/include -I.    -DIS_UTF8_LOCALE=1 -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/Rcpp/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/stringfish/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppParallel/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include   -I/opt/local/libexec/onetbb/include -DTBB_INTERFACE_NEW -fPIC  -pipe -Os -arch ppc   -c RcppExports.cpp -o RcppExports.o
> 
> > /opt/local/bin/g++-mp-13 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DRCPP_NO_SUGAR -I../inst/include -I.    -DIS_UTF8_LOCALE=1 -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/Rcpp/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/stringfish/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/RcppParallel/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include   -I/opt/local/libexec/onetbb/include -DTBB_INTERFACE_NEW -fPIC  -pipe -Os -arch ppc   -c qx_functions.cpp -o qx_functions.o
> 
> > In file included from qx_functions.cpp:11:
> 
> > io/multithreaded_block_module.h:280:16: error: 'source_node' in namespace 'tbb::flow' does not name a template type
> 
> >   280 |     tbb::flow::source_node<OrderedBlock> reader_node;
> 
> >       |                ^~~~~~~~~~~
> 
> > io/multithreaded_block_module.h: In constructor 'BlockCompressReaderMT<stream_reader, decompressor, E>::BlockCompressReaderMT(stream_reader&)':
> 
> > io/multithreaded_block_module.h:306:5: error: class 'BlockCompressReaderMT<stream_reader, decompressor, E>' does not have any field named 'reader_node'
> 
> >   306 |     reader_node(this->myGraph,
> 
> >       |     ^~~~~~~~~~~
> 
> > io/multithreaded_block_module.h:363:30: error: 'reader_node' was not declared in this scope
> 
> >   363 |         tbb::flow::make_edge(reader_node, decompressor_node);
> 
> >       |                              ^~~~~~~~~~~
> 
> > make: *** [qx_functions.o] Error 1
> 
> > ERROR: compilation failed for package ‘qs2’
> 
> > ```
> 
> 
> 
> Hopefully fixed with the latest commit. Tested on the latest version of TBB. 
> 
> 
> 
> `remotes::install_github("traversc/qs2", ref= "df9e1cd902a6a461bc7cc6783f716b4983e4e4fc", configure.args = " --with-TBB --with-simd=AVX2")`

Thank you, I will try it.

**Comment by barracuda156** [comment]
From df9e1cd902a6a461bc7cc6783f716b4983e4e4fc it works fine:
```
36-242% port installed R-qs2
The following ports are currently installed:
  R-qs2 @0.1.1_0 (active)

36-242% otool -L /opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/qs2/libs/qs2.so
/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/qs2/libs/qs2.so:
	qs2.so (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libMacportsLegacySupport.dylib (compatibility version 1.0.0, current version 1.3.0)
	/opt/local/lib/libgcc/libatomic.1.dylib (compatibility version 4.0.0, current version 4.0.0)
	/opt/local/lib/libzstd.1.dylib (compatibility version 1.0.0, current version 1.5.6)
	/opt/local/libexec/onetbb/lib/libtbb.12.dylib (compatibility version 12.0.0, current version 12.13.0)
	/opt/local/libexec/onetbb/lib/libtbbmalloc.2.dylib (compatibility version 2.0.0, current version 2.13.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 511.1.0)
	/opt/local/lib/libgcc/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.34.0)
	/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/lib/libR.dylib (compatibility version 4.4.0, current version 4.4.1)
	/opt/local/lib/libgcc/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 117.0.0)
```
Thank you!

**Comment by traversc** [comment]
I'd recommend this which should be compatible with newer TBB versions:

`remotes::install_github("traversc/qs2", configure.args = "--with-TBB")`

Glad I can help!
